### ISSUE TITLE
add macro annotation to generate Prism for sealed trait

### ISSUE THREAD

**Issue by julien-truffaut** [optics-dev/Monocle#281]
``` scala
@Prisms
sealed trait Foo
case class Bar(i: Int) extends Foo
case class Baz(s: String) extends Foo
```

Should generate the following code:

``` scala
object Foo {
  val bar: Prism[Foo, Bar] = GenPrism[Foo, Bar]
  val baz: Prism[Foo, Baz] = GenPrism[Foo, Baz]
}
```

**Comment by cb372** [comment]
I [started work](https://github.com/cb372/Monocle/commit/5a3a193a52fe1515d8f3535c3525d446bb19e0e8) on this and got far enough to confirm (after discussing with @milessabin) that it's not possible with a macro annotation 😢 

The macro relies on `knownDirectSubclasses` to find `Bar` and `Baz`, but because the macro annotation is expanded before the typer runs, the compiler doesn't know about those classes yet.

I'd like to come back to this if/when [Miles's proposed fix for SI-7046](https://github.com/scala/scala/pull/5284) is merged.

**Comment by julien-truffaut** [comment]
We could test `knownDirectSubclasses` fix using https://github.com/typelevel/scala

**Comment by milessabin** [comment]
Nb. it's your downstream users which would need to use Typelevel Scala, ie. it's the code which defines the ADT which needs to be compiled with TLS.

**Comment by milessabin** [comment]
But, yes, please do try that :-)

**Comment by milessabin** [comment]
FWIW, I'm going to recommend on shapeless's README that anyone working with ADTs and `Generic` should use TLS until my fix (or a better one) is merged. Risk is very low.

**Comment by julien-truffaut** [comment]
You're right, I was just suggesting to test your fix with @cb372 macro implementation as it is not part of monocle yet. If it works, we can add something in the readme to tell users to use typelevel scala for this macro annotation to work.

**Comment by cb372** [comment]
It works! Using TLS, `knownDirectSubclasses` now finds the subclasses as expected.

My macro annotation now appears to be generating sensible code but fails with a vague "macro annotation could not be expanded". I need to investigate further, but it's definitely caused by a separate issue. I can tell from my debug logging that `knownDirectSubclasses` is working fine.

**Comment by milessabin** [comment]
@cb372 please add a :+1: to the [PR](https://github.com/scala/scala/pull/5284) if you haven't already :-)

**Comment by julien-truffaut** [comment]
@cb372 can I or anyone else help you with the error you got after the macro expanded?

**Comment by cb372** [comment]
I don't remember the details now, but I'll try to resurrect my branch and put together a StackOverflow question later this week

**Comment by julien-truffaut** [comment]
Awesome, thanks Chris

**Comment by cb372** [comment]
@julien-truffaut @milessabin http://stackoverflow.com/questions/39916994/please-help-me-debug-my-macro-annotation 🙏

**Comment by julien-truffaut** [comment]
we should give it another try with scala 2.12.1

**Comment by cb372** [comment]
I just couldn't let this one go 😄 

Here's a proof of concept of something I got working by doing crazy things with a whitebox def macro and `Dynamic`. If this looks useful, I can make a PR.

https://github.com/cb372/prisms/blob/master/src/test/scala/example/Example.scala

/cc @davegurnell

**Comment by julien-truffaut** [comment]
@cb372 that's awesome! Does it need to be a maro annotation or could it be something like the macro Lens syntax from @cvogt https://github.com/julien-truffaut/Monocle/blob/master/macro/shared/src/main/scala/monocle/macros/syntax/GenApplyLensSyntax.scala#L6

**Comment by cb372** [comment]
@julien-truffaut No, it doesn't need to be an annotation. That implicit conversion is a nice idea, I'll try it.

**Comment by julien-truffaut** [comment]
This probably should be considered on another iteration but it would be great if we could compose `.lens` and `.prism`, e.g.

```
case class Computer(name: String, )
sealed trait OS
case class Linux(version: String) extends OS
case class Windows(version: String, licence: String) extends OS

val c = Computer("foo", Windows("7", "12345"))
c.lens(_.os).prism[Windows].lens(_.licence)
```

**Comment by cvogt** [comment]
`.lens` currently only supports `a.lens(_.b.c)`, but I'd be happy to contribute support for `a.lens(_.b).lens(_.c)`.

**Comment by julien-truffaut** [comment]
No macro annotations in Scala 3
