### ISSUE TITLE
How should we differentiate dangerous methods?

### ISSUE THREAD

**Issue by julien-truffaut** [optics-dev/Monocle#786]
Optics, like most functional programming concepts, follow some principles (also called laws). FP libraries tend to have two kinds of operations:
Constructors, where users need to verify the constructed object, follow those rules, usually via property-based testing.

Combinators, where users are guaranteed properties are preserved. For example, if you have a valid optic, applying any combinator gives you another correct optic.
Now, the problem is that some methods are incredibly convenient for users, but they may break optics principles. // TODO add examples.

In Monocle 1.x and 2.x, we told users: "Sorry, we understand what you want. It is useful but potentially unsafe, so we don't put this in the library". It has been very frustrating to users. In my opinion, we should allow those combinators, but we need a way to mark them as dangerous. 

Many libraries use `unsafe` prefix, e.g. `unsafeFilter`. Other languages use a `!` suffix like `filter!`. Ideally, it shouldn't be too verbose.

**Comment by tpdi** [comment]
One thing I've done is to use a different, unsafe interface. This means the client programmer must explicitly indicate s/he wants to use unsafe operations, which a) removes any surprise on the part of the client programmers and b) makes it easier for them to search for unsafe usage later than by searching for each unsafe method name individually.

I've written up **two** examples here, one than can be used to retroactively make a library safer, and one that is stricter: https://github.com/tpdi/examples/blob/master/src/main/scala/org/diffenbach/unsafely/Safe.scala

**Comment by julien-truffaut** [comment]
@tpdi good idea, but one thing a bit annoying with that approach is that you don't know which methods may be unsafe. For example, you could refactor your code and not need it anymore but you wouldn't know.

**Comment by tpdi** [comment]
I'm not sure I follow. Is "you" in this case the client programmer?I'd think they would know what's unsafe, because in order to call those methods, they'd first have to call .asUnsafe():var x = someLens()x.asUnsafe().unsafeMethod()Perhaps you're saying that if they write a method that relies on an unsafe method, their method might take a reference to the unsafe interface (rather than calling .asUnsafe in that method):def clientMethod(ulens: UnsafeLens) = {     ulens.unSafeMethod()}Then they refactor:def clientMethod(ulens: UnsafeLens) = {     ulens.safeMethod()}  // whoops still passing an UnsafeLens, now unnecessarily If that's what you're referring to, my second example (disjoint interfaces) addresses it, because with that, it's also not possible to call safe operations on the unsafe interface.The cost of that is that the client programmer will have to call the interface swapping methods more often when mixing safe and unsafe operations. But that's what you want, if you want to sensitize them to which methods are unsafe.Thanks,Tom
-------- Original message --------From: Julien Truffaut <notifications@github.com> Date: 5/30/20  12:07  (GMT-08:00) To: optics-dev/Monocle <Monocle@noreply.github.com> Cc: TP Diffenbach <tpd@diffenbach.org>, Mention <mention@noreply.github.com> Subject: Re: [optics-dev/Monocle] How should we differentiate dangerous
  methods? (#786) 
@tpdi good idea, but one thing a bit annoying with that approach is that you don't know which methods may be unsafe. For example, you could refactor your code and not need it anymore but you wouldn't know.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/optics-dev/Monocle/issues/786#issuecomment-636371744",
"url": "https://github.com/optics-dev/Monocle/issues/786#issuecomment-636371744",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by julien-truffaut** [comment]
@tpdi Yes, I meant the user of the library may not know which method is safe or not. I see what you mean with disjoint interfaces but I see two issues:
1. we shouldn't allow going from `UnsafeOptic` to `SafeOptic`
1. it makes the API quite verbose

**Comment by julien-truffaut** [comment]
The plan for now is to add documentation.
